"""make buying_price mandatory, rename selling_price alias to sellingPrice

Revision ID: 17e0bc8f2042
Revises: 45b2f0f0683d
Create Date: 2026-06-27 20:14:34.346935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e0bc8f2042'
down_revision: Union[str, Sequence[str], None] = '45b2f0f0683d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE products SET buying_price = 0 WHERE buying_price IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'buying_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'buying_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    # ### end Alembic commands ###
