"""add shops and stocks tables

Revision ID: 45b2f0f0683d
Revises: aeddf5317b56
Create Date: 2026-06-27 20:06:30.313302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b2f0f0683d'
down_revision: Union[str, Sequence[str], None] = 'aeddf5317b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=True)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('stock_keeper_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_keeper_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_cashier_id'), 'stocks', ['cashier_id'], unique=False)
    op.create_index(op.f('ix_stocks_shop_id'), 'stocks', ['shop_id'], unique=False)
    op.create_index(op.f('ix_stocks_stock_keeper_id'), 'stocks', ['stock_keeper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_stock_keeper_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_shop_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_cashier_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###
