"""remove product barcode and description, scan by sku instead

Revision ID: 66b9a5bdb599
Revises: e3c23519a5cc
Create Date: 2026-06-28 21:06:31.760534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b9a5bdb599'
down_revision: Union[str, Sequence[str], None] = 'e3c23519a5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_column('products', 'description')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    # ### end Alembic commands ###
