"""drop stock movement reason

Revision ID: 8902afd712c8
Revises: ee39da6869e7
Create Date: 2026-06-26 16:44:48.601691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8902afd712c8'
down_revision: Union[str, Sequence[str], None] = 'ee39da6869e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
