"""add manager/stock_keeper roles, purchase orders, product quantity_unit and optional barcode/buying_price

Revision ID: aeddf5317b56
Revises: 8902afd712c8
Create Date: 2026-06-27 19:51:22.622971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeddf5317b56'
down_revision: Union[str, Sequence[str], None] = '8902afd712c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'manager'")
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'stock_keeper'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_type', sa.Enum('package', 'detail', name='purchase_type'), nullable=False),
    sa.Column('scanned_code', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_unit', sa.String(length=32), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_product_id'), 'purchase_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_received_by_id'), 'purchase_orders', ['received_by_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_scanned_code'), 'purchase_orders', ['scanned_code'], unique=False)
    op.add_column('products', sa.Column('quantity_unit', sa.String(length=32), server_default='pcs', nullable=False))
    op.alter_column('products', 'barcode',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('products', 'buying_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'buying_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('products', 'barcode',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('products', 'quantity_unit')
    op.drop_index(op.f('ix_purchase_orders_scanned_code'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_received_by_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_product_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
