"""revert category_id to required

Revision ID: beb377680d79
Revises: f9dd1e0ede43
Create Date: 2026-06-28 21:32:00.685014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb377680d79'
down_revision: Union[str, Sequence[str], None] = 'f9dd1e0ede43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE products SET category_id = (SELECT MIN(id) FROM categories) WHERE category_id IS NULL")

    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
