"""add shop manager, product stock scoping, receipts

Revision ID: c6c1b1a4e2e2
Revises: 17e0bc8f2042
Create Date: 2026-06-27 21:06:30.104822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c1b1a4e2e2'
down_revision: Union[str, Sequence[str], None] = '17e0bc8f2042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=32), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('checked_out_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='ck_receipts_total_amount_non_negative'),
    sa.ForeignKeyConstraint(['checked_out_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_checked_out_by_id'), 'receipts', ['checked_out_by_id'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=True)
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_receipt_items_quantity_positive'),
    sa.CheckConstraint('subtotal >= 0', name='ck_receipt_items_subtotal_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_receipt_items_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_product_id'), 'receipt_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_receipt_items_receipt_id'), 'receipt_items', ['receipt_id'], unique=False)
    op.add_column('products', sa.Column('stock_id', sa.Integer(), nullable=True))
    op.execute("UPDATE products SET stock_id = (SELECT MIN(id) FROM stocks) WHERE stock_id IS NULL")
    op.alter_column('products', 'stock_id', nullable=False)
    op.create_index(op.f('ix_products_stock_id'), 'products', ['stock_id'], unique=False)
    op.create_foreign_key(None, 'products', 'stocks', ['stock_id'], ['id'], ondelete='RESTRICT')
    op.add_column('shops', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shops_manager_id'), 'shops', ['manager_id'], unique=False)
    op.create_foreign_key(None, 'shops', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_index(op.f('ix_shops_manager_id'), table_name='shops')
    op.drop_column('shops', 'manager_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_stock_id'), table_name='products')
    op.drop_column('products', 'stock_id')
    op.drop_index(op.f('ix_receipt_items_receipt_id'), table_name='receipt_items')
    op.drop_index(op.f('ix_receipt_items_product_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_checked_out_by_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
