"""shop create now uses shopName, address, phone, optional email

Revision ID: e3c23519a5cc
Revises: e70eaae88cb8
Create Date: 2026-06-28 17:13:55.276554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c23519a5cc'
down_revision: Union[str, Sequence[str], None] = 'e70eaae88cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('shops', sa.Column('address', sa.String(length=255), server_default='', nullable=False))
    op.add_column('shops', sa.Column('phone', sa.String(length=32), server_default='', nullable=False))
    op.add_column('shops', sa.Column('email', sa.String(length=255), nullable=True))
    op.execute("UPDATE shops SET address = COALESCE(location, '')")
    op.drop_column('shops', 'location')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('shops', 'email')
    op.drop_column('shops', 'phone')
    op.drop_column('shops', 'address')
    # ### end Alembic commands ###
