"""add full CRUD support to shops (soft delete)

Revision ID: e70eaae88cb8
Revises: c6c1b1a4e2e2
Create Date: 2026-06-27 21:11:50.184593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70eaae88cb8'
down_revision: Union[str, Sequence[str], None] = 'c6c1b1a4e2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('shops', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'deleted_at')
    op.drop_column('shops', 'is_deleted')
    # ### end Alembic commands ###
